//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practika.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public string C__Policy { get; set; }
        public string C__Receipts { get; set; }
        public string Date_of_issue { get; set; }
        public double Price { get; set; }
        public long Phone_number { get; set; }
        public string Address { get; set; }
    }
}
